### ISSUE TITLE
Create list of required packages

### ISSUE THREAD

**Issue by jwreep** [Goobley/Lightweaver#18]
For install purposes, it would be useful to have a list of which packages are required.  I'm setting up a new virtual environment and keep missing which ones are necessary. . .

**Comment by Goobley** [comment]
`environment.yml` in the root directory should have all the packages necessary to run. A few things like the model atom converter in tools will require extra packages, but there shouldn't be anything else needed to run lightweaver.
Using conda you can create a new virtual environment with these packages by doing `conda env create -f environment.yml` which will create an environment called `LightweaverDev`.

**Comment by jwreep** [comment]
Missed that!  That's exactly what I'm looking for.
