### ISSUE TITLE
Add __init__.py file

### ISSUE THREAD

**Issue by wtbarnes** [Goobley/Lightweaver#2]
The `lightweaver` directory should contain a `__init__.py` file so that modules can be imported using the syntax `from lightweaver.<module_name> import <function_or_class_name>`.

**Comment by Goobley** [comment]
Is this still necessary? I thought after the changes in (https://www.python.org/dev/peps/pep-0420/ -- python3.3) an `__init__.py` was unnecessary if it would be empty. Lightweaver requires 3.7+ due to the typing features and dataclasses.

**Comment by wtbarnes** [comment]
Oh I was not aware of that pep. Maybe so?

**Comment by Goobley** [comment]
I haven't needed the `__init__.py` so far, but I'm not sure what best practice is. Either way, I will be moving some of the cython stuff from `lightweaver.LwCompiled` (there's a reason it doesn't match proper naming convention) probably to be made available through the `__init__.py` -- so I'll leave this open for now.

**Comment by Goobley** [comment]
`__init__.py` has been added now. Most components should be usable from `import lightweaver as lw`, numpy-esque. Samples will be updated to reflect this soon.
