### ISSUE TITLE
Scripts in Samples directory are out of date

### ISSUE THREAD

**Issue by wtbarnes** [Goobley/Lightweaver#3]
The imports in the `Test2.py` script in `Samples/`do not reflect the current structure of the package. Doing the following gets me most of the way there:

* Created `lightweaver/__init__.py` (See #2)
* Prepended imports with `lightweaver.<module_name>

However, there's one module that I cannot seem to find anywhere else in the repo:

```python
from PyProto import ComputationalAtom, background, gamma_matrices, stat_equil
```

I noticed that on some of the other branches, there is a `PyProto.py` file in the root of the repo. However, I can't seem to find the imported classes/functions (i.e. `ComputationalAtom, background, gamma_matrices, stat_equil`) on the master branch. Has the workflow for doing these calculations changed?

I'm happy to submit a PR to fix the examples.

**Comment by wtbarnes** [comment]
ping @jwreep

**Comment by Goobley** [comment]
Ah, yes, the old examples are very much stale, and shouldn't be on master any more. Since splitting lw into its own package I have moved (the working) Samples to a [repository](https://github.com/Goobley/LightweaverSamples), but had forgotten to remove the old ones from master. That's on me, I'll get rid of them.

**Comment by jwreep** [comment]
Using the proper environment helped as well . . . 

In the new samples, I still have issues.  Copying and pasting from Test12.py for example:

>>> from lightweaver.LwCompiled import LwContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'lightweaver.LwCompiled'

Any idea?

**Comment by Goobley** [comment]
How did you install it? That should be installed during the compilation step. For bash (on linux), the invocation should be something akin to `CXX="g++8 -pthread"; CC="g++8 -pthread"; LDSHARED="g++8 -pthread -shared"; python3 -m pip install -vvv -e .`. On macOS the system compilers should be new enough to roll out of the box. On Windows, specify the compiler and linker in whatever way seems most standard. Check the end of the output from the pip install command to check if it says successful or not.

**Comment by jwreep** [comment]
I'm working on macOS.

Installed through bash:
```
(base) Lightweaver-master jreep$ export CC='g++-9'
(base) Lightweaver-master jreep$ echo $CC
g++-9
(base) Lightweaver-master jreep$ python -m pip install -vvv -e .

```
The output does indeed say successfully installed:

```
    Installed /Users/jreep/Desktop/Python/Lightweaver-master
Successfully installed lightweaver

```

I just did a clean install to check it again.

**Comment by Goobley** [comment]
On linux I've found it necessary to also set `CXX` and `LDSHARED` as above. On macOS the default clang settings work well for me. Are you sure that the python you're invoking points to the one in your conda environment, and you've activated the correct environment? This install method has worked directly for me across a variety of mac and linux installs.

**Comment by Goobley** [comment]
Maybe check to see if some sort of shared library is being created in the Lightweaver/lightweaver directory, if not then something concerning is going on.

**Comment by jwreep** [comment]
I don't know what I did differently, but I managed to get it to work this time.  I think I improperly installed it before, and after cleaning up the environment and starting fresh, it now seems to work.  Thanks @Goobley

**Comment by Goobley** [comment]
The scripts in the [LightweaverSamples](https://github.com/Goobley/LightweaverSamples), have been updated, and quite a few new ones have been added (see `Simple*.py` therein). They're not documentation, but a step in the right direction.
The installation procedure still isn't what I would like, but I will open a new issue for that.
