### ISSUE TITLE
Calculating Stokes parameters for 8542 example gives `ValueError`

### ISSUE THREAD

**Issue by wtbarnes** [Goobley/Lightweaver#30]
I'm trying to adapt the simple example in the gallery to calculate the Stokes parameters for a constant magnetic field (as a function of z). Besides passing `stokes=True` to `compute_rays`, all of the code from the example is the same. I've then modified the atmosphere as follows,

```python
atmos_const_b = Falc82()
atmos_const_b.B = 0.05 * np.ones(atmos_const_b.z.shape)
atmos_const_b.gammaB = 0.78539819 * np.ones(atmos_const_b.B.shape)
atmos_const_b.chiB = np.zeros(atmos_const_b.B.shape)
```

Running `synth8542` with this atmosphere, I then get the following exception,

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-147-63eb88a56916> in <module>
----> 1 ctx, IQUV_B_const = synth_8542(
      2     atmos_const_b,
      3     conserve=False,
      4     useNe=False,
      5     wave=wave_caII,

<ipython-input-91-f7bfabc22d02> in synth_8542(atmos, conserve, useNe, wave, stokes)
     73     # compute the final intensity for mu=1 on the provided wavelength grid.
     74     eqPops.update_lte_atoms_Hmin_pops(atmos)
---> 75     Iwave = ctx.compute_rays(wave, [atmos.muz[-1]], stokes=stokes)
     76     return ctx, Iwave
     77 

Source/LwMiddleLayer.pyx in lightweaver.LwCompiled.LwContext.compute_rays()

ValueError: could not broadcast input array from shape (3,1000,1,1) into shape (3,1000)
```

I'm not really sure where this dimension mismatch is coming from. It looks like some extra dimensions need to be added or squeezed somewhere to account for the fact that this is a 1D atmosphere?

**Comment by Goobley** [comment]
Your interpretation is correct, and I have no idea how this regression has lasted as long as it has. I've pushed a fix, I have a couple of other small things to look at, and will trigger a new release in ~1 hour.
