### ISSUE TITLE
RuntimeError on import with Numpy v1.22

### ISSUE THREAD

**Issue by OfAaron3** [Goobley/Lightweaver#41]
Currently `install_requires` has `numpy>=1.19`, however, I get the following RuntimeError on import 

![lightweaver](https://github.com/Goobley/Lightweaver/assets/22356218/0e0576fb-37ba-4ec8-9faf-17d1dc3e9798)

This error was resolved by upgrading to Numpy v1.24.4.

**Comment by Goobley** [comment]
This is linked to the version the code is built against in the CI environmnet. I will look at building against the lowest supported version. Good catch.

**Comment by Goobley** [comment]
Should be fixed by e2fa850 and available in the next binary release.
